# Form implementation generated from reading ui file 'D:\Users\LENOVO\baicuaThao\ProjectFinal\User\UserFunction\UserFunction.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1173, 809)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -5, 1171, 761))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\Users\\LENOVO\\baicuaThao\\ProjectFinal\\User\\UserFunction\\../../image/User function.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButtonReadReview = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonReadReview.setGeometry(QtCore.QRect(630, 500, 151, 61))
        self.pushButtonReadReview.setStyleSheet("")
        self.pushButtonReadReview.setText("")
        self.pushButtonReadReview.setFlat(True)
        self.pushButtonReadReview.setObjectName("pushButtonReadReview")
        self.pushButtonReadFanfic = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonReadFanfic.setGeometry(QtCore.QRect(810, 500, 151, 61))
        self.pushButtonReadFanfic.setStyleSheet("")
        self.pushButtonReadFanfic.setText("")
        self.pushButtonReadFanfic.setFlat(True)
        self.pushButtonReadFanfic.setObjectName("pushButtonReadFanfic")
        self.pushButtonWriteScript = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonWriteScript.setGeometry(QtCore.QRect(990, 500, 151, 61))
        self.pushButtonWriteScript.setStyleSheet("")
        self.pushButtonWriteScript.setText("")
        self.pushButtonWriteScript.setFlat(True)
        self.pushButtonWriteScript.setObjectName("pushButtonWriteScript")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1173, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
