from libs.JsonFileFactory import JsonFileFactory
from models.Draft import Draft

draft=[]
draft.append(Draft("The End", "Hayakawa Aki", "11/01/2025", "Phạm Quốc Bảo","Aki spent his entire trip to Hokkaido thinking about you. When his thoughts begin to wander like this, he isn't given much of a choice; you occupy every space in his mind. Each stream of consciousness always seems to lead right back where he left it — You.Hokkaido is cold, empty, and manages to suck the life out of everything it touches. The sky is a certain shade of melancholy blue and twilight. It's the kind of atmosphere that causes him to slip into his usual routine of drowning in old, tired memories and his own reflections. His heart and his brain don't spare him much pity these days.Frost creeps at the edges of the windows. A veil of snow falls incessantly and swirls with the wind, obscuring any semblance of a view, leaving him only able to see what lingers in the back of his mind: graves made of polished stone, loaded guns, failed attempts to quit smoking, forgetting how to say a prayer because it's been too long. Getting cold feet, and trying to live an honest life, even though you know it's far too late for that. "))
draft.append(Draft("Manacled", "Oliver Queen, Felicity Smoak", "14/02/2025", "Phạm Quốc Bảo","Her head hurt. It was becoming a problem, just how often that was happening these days. She’d had some pretty good knocks to the head, and even though she knew that all of the myths about killing brain cells and stuff were just that, head injury was something she’d done a lot of research on ever since joining Team Arrow—if Oliver didn’t like the nickname, he could very well come up with his own—since her position on the team vacillated between excising dead tissue and excising troublesome code. So she’d done her reading, okay? And waking up with her head pounding like this, not a good thing. Not a good thing at all."))
draft.append(Draft("Mumu", "Le Sarongla, Vacorina", "28/02/2025", "Hồ Quang Dũng","When they said life after death, Lea didn’t take that quite literally that she’d be stuck in a place where nobody could see her. She thought she was going straight to the heavens (God forbid she falls down the pit) but on the contrary, there she was, in limbo, being able to touch, feel, and see (she hoped she could eat but the food just kept on passing through) but nobody could see her. In short, she was a ghost. Although it did come with perks, like being able to watch a concert for free, it did tend to get a little too boring. She thought she’d meet new ghost besties but as it turned out, she was all alone. So what she did... well what did ghost do? She had no idea. When she was alive, there would have been a multitude of things to do, in fact, her to-do-list never really ran out. But now that she was a mumu , she was left empty-handed. She didn’t imagine ghost life to be quite boring but then she realized that she could stir up mischief and nobody would know it was her. When she was alive, she was a goody-two-shoes, that is she feared consequences. But turn about was a fair play, and being literally invisible gave her a pass to do whatever she wanted (except eat, something she was still pissed off about)."))

draft.append(Draft("The Enigma of Shadows", "Rhea, Orion, Lysander", "10/05/2020", "Phạm Quốc Bảo","Rhea, a skilled thief, stumbles upon a hidden artifact that grants her unimaginable power. With Orion, a mysterious guardian, and Lysander, a rival thief, she must decide whether to use it for good or succumb to its dark allure. As the artifact's secrets unfold, she finds herself ensnared in a deadly game of fate.Copyright is a limited right, with key exceptions such as fair use. Fair use allows people to use copyrighted works for transformative purposes, such as commenting, reporting, and criticizing."))
draft.append(Draft("The Enchanted Forest", "Maris, Cedric, Finnian", "27/03/2018", "Phạm Quốc Bảo", "Maris, a young girl with a special connection to nature, discovers an enchanted forest filled with magical creatures. With Cedric, a brave knight, and Finnian, a mischievous sprite, she must protect the forest from dark forces.Vancouver wasn’t horrible. While it was embarrassing to say out loud, she loved the maple in Canada. It wasn’t anything like she’d ever tasted back in the States, and being able to take the snow from winter and pour the hot maple into it made for a nostalgic treat. She was lucky to find out that Michigan had a generous amount of snowfall, but it never did taste right with the redhead when she tried to make it again."))
draft.append(Draft("The Darkest Hour", "Cassiel, Rowena, Gareth", "25/08/2014", "Phạm Quốc Bảo", "Cassiel, a fallen angel, must confront his past to save the world from an impending darkness. With Rowena, a fierce warrior, and Gareth, a loyal friend, they embark on a journey of redemption.Written by two hotdogs to spread the word of Brian! This is the bible without all the lies, character changes, and withholding of the truth. We are loosing braincells by teh second im hemmoraging rn that half off clairs lobotomy behind the mall was not it are are synced like bluetooth headphones."))
draft.append(Draft("The Dragon's Treasure", "Astra, Kael, Draven", "23/06/2023", "Phạm Quốc Bảo", "Astra, a dragon shifter, must embrace her heritage to protect her kind. With Kael, a dragon prince, and Draven, a fierce warrior, they embark on a quest to reclaim their lost legacy.Welcome to Unholy Verse, my wacky AU meant to explore my favorite ships and focus on an actual story. Lots of headcanons and projection may play a part into the world I have built, most of the story follows canon, so most of these chapters will be rewrites of episodes that are different in my AU. As much as this AU sticks to light topics and nothing too dark, there will be some heavy topics in this story, especially towards the end."))
#Chưa post
draft.append(Draft("Dance, Dance, Dance", "Kise Ryouta, Kuroko Tetsuya, Kagami Taiga, Momoi Satsuki, Aomine Daiki", "01/12/2012", "Phạm Quốc Bảo","In the middle of June, they stacked piles of worn wood and leftover banners in the center of the field; the bonfire, they would build after sports day came and went. In the meantime, with the sun half-concealed by the horizon and the students assembled round the grounds, Kuroko stayed in the third year classroom and watched the girls line up to dance with the boys, a flurry of white and movement across the soccer field.Off to the side, Akashi stood conversing with the captain of the tennis club. Murasakibara, hulking and lax with partners, a contrast to Midorima's precise stiffness, his awkwardness, was easier to find, with his height and the wide berth the other students gave him. Momoi was only harder to search for, but barely. With her wrist caught and her feet guided with little ease by Aomine, she threw back her head; she might have been laughing, then."))
draft.append(Draft("Justice", "Jedi Knight, Leeha Narezz", "08/12/2018", "Phạm Quốc Bảo","“Rivka? May I come in?”.The voice was soft, cautious not to startle her; though Rivka had sensed her presence before she spoke nonetheless. “The Meedees said you seemed upset.”.Rivka pressed the button to open the door from across the room, and shifted on the bed.“Not that I don’t appreciate the sentiment, but - not like that’s exactly newsworthy, these days,” she replied, watching as Leeha moved into her - their - quarters.Rivka shrugged. “Well everything’s completely fucked to hell, isn’t it,” she said flatly, after a few moments’ silence. “A soldier who’s destined to save her people by creating peace, while the Order that’s supposed to keep peace sends it’s members out to fight a war? The fact that we would interfere in a people’s life, leave, and then condemn what they’d become when we came back like it was all their doing?” "))
#Chờ duyệt
draft.append(Draft("The End", "Hayakawa Aki", "11/01/2025", "Phạm Quốc Bảo","Aki spent his entire trip to Hokkaido thinking about you. When his thoughts begin to wander like this, he isn't given much of a choice; you occupy every space in his mind. Each stream of consciousness always seems to lead right back where he left it — You.Hokkaido is cold, empty, and manages to suck the life out of everything it touches. The sky is a certain shade of melancholy blue and twilight. It's the kind of atmosphere that causes him to slip into his usual routine of drowning in old, tired memories and his own reflections. His heart and his brain don't spare him much pity these days.Frost creeps at the edges of the windows. A veil of snow falls incessantly and swirls with the wind, obscuring any semblance of a view, leaving him only able to see what lingers in the back of his mind: graves made of polished stone, loaded guns, failed attempts to quit smoking, forgetting how to say a prayer because it's been too long. Getting cold feet, and trying to live an honest life, even though you know it's far too late for that. "))
draft.append(Draft("Manacled", "Oliver Queen, Felicity Smoak", "14/02/2025", "Phạm Quốc Bảo","Her head hurt. It was becoming a problem, just how often that was happening these days. She’d had some pretty good knocks to the head, and even though she knew that all of the myths about killing brain cells and stuff were just that, head injury was something she’d done a lot of research on ever since joining Team Arrow—if Oliver didn’t like the nickname, he could very well come up with his own—since her position on the team vacillated between excising dead tissue and excising troublesome code. So she’d done her reading, okay? And waking up with her head pounding like this, not a good thing. Not a good thing at all."))

draft.append(Draft("The Shattered Crown", "Isolde, Cedric, Alaric", "22/03/2021", "Phạm Thị Yến","In a realm torn by civil war, Isolde, the rightful heir, must reclaim her throne from her treacherous uncle Cedric and the enigmatic Alaric, who holds secrets that could change the fate of the kingdom forever. Along the way, she uncovers long-buried betrayals and faces impossible choices that will determine her legacy.Copyright is the legal protection granting the owners of creative works (such as books, music, artwork, and so on) the authority to control their use, distribution, and sale."))
#Chưa post
draft.append(Draft("Rivka Journey", "Rivka", "28/03/2023", "Phạm Thị Yến","Leeha moved to sit on the side of the bed, subdued and pensive. “I don’t want Master Sedoru to be forced to do to the Republic soldiers what I did to Jomar,” she said quietly, after a few moments. “It is… important to me that he is stopped before it gets to that point.”Rivka squashed the thoughts buzzing against her mouth for the sake of sensitivity. Not that it was exactly easy - all they really did was slide back down into her stomach. In the Force, she reached out to find Leeha’s presence, trying to convey a reassuring sympathy and understanding, and certainty. Not something she felt herself, but that scarcely fazed her lately."))
draft.append(Draft("Hey Hey", "John Egbert, Dave Strider, Dirk Strider", "17/09/2024", "Phạm Thị Yến","It was little over a year ago you had begun the adoption process and it took almost everything out of you, eventually leaving you exhausted, anxious, and excited all at once. From the initial filing of papers to the background checks and interviews, even the inspection of your three bedroom home. But unlike most people, you did not have a spouse or significant other. You were, however, sure you had the capability to afford a child considering your profession.The one who gave you the idea to adopt was your cousin, Jake English. A few years before he had adopted a young girl named Jade, it was an odd choice that stood out to you because Jade had different additions compared to Jake. Where your cousin had more cat-like ears and tail, Jade had dog-like ears and tail. Although, now that you think about it, that might have been the decision of his then-girlfriend-now-wife Jane. It confused you as to why they would adopt instead of trying for their own. You shake your head. Maybe she is infertile?"))

#chờ duyệt
draft.append(Draft("Vampire", "Steve Harrington, Eddie Munson", "22/02/2025", "Phạm Thị Yến","It has been exactly fifteen days, eight hours and twenty-seven minutes since Eddie managed to miraculously survive being eaten alive. It has also been exactly fourteen days, eight hours and twenty-seven minutes since he realised that he wants to fucking bite Steve Harrington. And not in the cute way.Because sure, he can be honest here – it isn’t the first time he has played around with the thought of biting into the tanned skin on Steve’s neck. He’s not blind, his sight is damn near perfect – however impossible it sounds, it somehow improved since his Upside Down visit, but he is meticulously shoving this piece of information into the back of his mind – and Steve hasn’t spent a day in his life being unattractive. Some people are just meant to walk around looking as perfect as a Greek statue."))
draft.append(Draft("Hey Hey", "John Egbert, Dave Strider, Dirk Strider", "17/01/2025", "Phạm Thị Yến","It was little over a year ago you had begun the adoption process and it took almost everything out of you, eventually leaving you exhausted, anxious, and excited all at once. From the initial filing of papers to the background checks and interviews, even the inspection of your three bedroom home. But unlike most people, you did not have a spouse or significant other. You were, however, sure you had the capability to afford a child considering your profession.The one who gave you the idea to adopt was your cousin, Jake English. A few years before he had adopted a young girl named Jade, it was an odd choice that stood out to you because Jade had different additions compared to Jake. Where your cousin had more cat-like ears and tail, Jade had dog-like ears and tail. Although, now that you think about it, that might have been the decision of his then-girlfriend-now-wife Jane. It confused you as to why they would adopt instead of trying for their own. You shake your head. Maybe she is infertile?"))

#Đã post
draft.append(Draft("The Alchemist's Secret", "Mira, Rowan, Thalia", "30/09/2021", "Nguyễn Thị Linh","Mira, a talented alchemist, uncovers a secret formula that could change the world. With Rowan, her childhood friend, and Thalia, a rival alchemist, she must protect her discovery from those who seek to exploit it. As rival factions close in, she is faced with an impossible choice between knowledge and power.Due to exposure to the nuclear weapons, some children were born with abilities. A child begins to show their powers around age 8 if they are going to develop them and they are then sent to the Institute where they are forced to obey strict rules, their powers are bound with manacles around their wrists."))
draft.append(Draft("The Lost City", "Cassian, Elara, Felix", "05/10/2021", "Nguyễn Thị Linh", "Cassian, an adventurous archaeologist, discovers a lost city filled with ancient secrets. With Elara, a fierce protector, and Felix, a charming rogue, they must uncover the truth before it falls into the wrong hands.The redhead’s face was heated up by that comment. She wasn’t sure if Kat understood what she meant by all that, but she took what she could get. If she was able to read anything about this woman, it was that she wasn’t the emotional type. Even if that was the case, Swann didn’t mind, and she could roll with the punches.During this he befriends Twilight and the other Elements of Harmony along with the many other ponies in Equestria. A story where laughter is shared, tears are shed, and the bonds of friendship and love are tested in this reimagining."))
#chưa post
draft.append(Draft("I, Myself", "Ed Warn, Lu Zack", "24/03/2024", "Nguyễn Thị Linh","The school board decided to be a dick about everything that went down and forbade them from playing in the drama room, so they had to look for another place. And sure, Gareth did offer up his garage, but it was already filled with their band equipment and even though his mom loved them to no end – with the kind of adoration that never ceased to surprise Eddie – they didn’t want to take advantage of her kindness. So, the Wheeler basement it was"))

#chờ duyệt
draft.append(Draft("Milord", "Mira,Uki,Lord Hert", "18/01/2025", "Nguyễn Thị Linh","It should’ve been easy, to say no that is. But when Eddie’s eyes met Steve’s – brown and golden and sincere and mesmerizing – he couldn’t utter a word. Fucking typical. If they were still in high school, he would mask his attraction as something else and sneer at Steve to chase him away, but he couldn’t do that now, could he?So here he is. And he is screwed, so, so, screwed. Because it’s one thing to stare at Steve from a safe distance, eyes trailing down his body and taking him in from afar. Being in his presence is a whole another deal, though.The noise of the opening door drags him out of his thoughts and there he stands, Steve Harrington in all his glory. He’s wearing one of his beloved striped polos and light blue jeans that just hug his thighs perfectly. His hair somehow looks carefully combed and equally tousled and soft and Eddie would give up his entire life to run his fingers through it."))


draft.append(Draft("The Ladyr", "Sibyss, Adril, Ela", "28/03/2018", "Bùi Đức Minh",'Sibyl, the last enchanter of her kind, must harness her dwindling powers to save her kingdom. With Adrian, a charming rogue, and Elara, a fierce warrior, she embarks on a quest to reclaim her magic.Looking at her age-old camcorder, Swann was close to throwing the ancient machine into the wall of her apartment. She’d been trying to load some of the footage she took in the park from a few days ago and unfortunately, it was giving her a shit time. The light on the camera kept blinking, and she sat back on her couch with defeat. It had been some time since she’d gotten it checked out, and she was sensing that a trip to the repair store was in order.'))
draft.append(Draft("The Shattered Mirror", "Nerissa, Orion, Thorne", "31/10/2018", "Bùi Đức Minh", "Nerissa, a gifted sorceress, discovers a shattered mirror that reveals alternate realities. With Orion, a brave knight, and Thorne, a cunning thief, she must piece together the truth before it's too late.What an odd sense of humor. Although it was different from any other conversation she’d have with any of the other people in the city, it felt oddly comforting to know there was someone else out here that was obliquer than normal. When she looked over at the bird, she expected it to still be there, but it was gone. Her curiosity got the best of her, and she walked over to the stone ledge to see where it might have gone. She peered her head over, and her eyes widened to see that the ground was farther down than she expected."))
draft.append(Draft("The Veil of Time", "Ezra, Celeste, Armand", "09/03/2020", "Bùi Đức Minh", "Ezra, a time traveler, discovers a plot to alter history. With Celeste, a brilliant historian, and Armand, a skilled warrior, they must race against time to preserve the timeline.A collection of fairy-tale oneshots with a twist. Beginning with a retelling of Cinderella-will eventually include such tales as Beauty and the Beast, East of the Sun and West of the Moon, Snow White, The Twelve Dancing Princesses, etc. Will be updating regularly and taking requests. Moderate to extreme AU and OOC. Ye have been warned."))
#chưa post
draft.append(Draft("Shifter", "Tony Stark, Bucky Barns", "07/03/2024", "Bùi Đức Minh","JARVIS pulled up page after page of research, and Tony’s head spun. There was so much information - and misinformation - about wolf shifters. He knew some, of course. He lived with two, but being roommates with a shifter was entirely different from... dating one. Or trying to date one.“Okay... cull out the obvious bullshit.”That still left him with a staggering amount of information to review. Well, he decided. He had become an expert in thermonuclear astrophysics overnight, he could do this too."))
draft.append(Draft("Charlotte", "Charlotte, Mary, Conell", "21/03/2022", "Bùi Đức Minh","Birds sang into the quiet morning as the Connell household slowly came to life. The front door of the mansion opened and a girl, no older than ten with a teddy bear in hand ran out.Different kinds of flowers bloomed in the vast lawn but only one flower held the girl's attention. Charlotte kneeled in front of a rose bush and she stared in awe as the petals glistened in the morning light. Small hands carefully encircled the stem and plucked out the flower from the bush and she wondered.'How does it feel like to be a plant?'"))

#chờ duyệt
draft.append(Draft("Delulu", "Loki, Thor", "17/01/2025", "Bùi Đức Minh","It had all started a few days ago when he saw his younger brother, Loki, getting out of a black luxury car parked discreetly at a corner, far from the view of their classmates. The driver, an older man with an extravagant demeanor, had exchanged a look with Loki before the boy hurried toward the school building. Thor hadn’t mentioned it at the time, but the image haunted him like a thorn lodged in his mind.Since then, Loki had been more distant than usual. Thor was used to his sarcasm and his way of keeping to himself, but now it seemed as though his brother was carrying a secret that was consuming him. That morning, as Thor passed by his locker, he noticed something strange: Loki was looking at his phone with an expression that flickered between anxiety and weariness. As Thor approached to greet him, Loki immediately turned off the screen and muttered an excuse before walking away. Thor sighed, leaning against the lockers. It wasn’t easy being the older brother of someone like Loki. There was always a wall between them, a barrier built over years of rivalry, secrets, and Loki’s relentless need to prove he didn’t need anyone. But Thor knew better. Something was wrong."))
draft.append(Draft("Infinity", "James Potter, Regulus Black", "04/02/2025", "Bùi Đức Minh","It's been nearly a week of days spent walking from dawn 'til dusk and nights spent sleeping restlessly on the forest floor, and James is starting to think that this quest of his maybe wasn't the best idea.It seemed simple enough in theory – travel north until he finds the shooting star he'd seen fall from the sky last Sunday, bring the star back with him to Godric's Hollow, and offer the star to Lily Evans in exchange for her hand in marriage, or her affection at the very least – but in practice it's proving more difficult. Perhaps he should have paid more attention to orienteering at school.Any hope he had of actually finding the star is dwindling as the sun sets on another day, when he sees what appears to be a glow on the horizon."))


draft.append(Draft("The STooPid Enchanter", "Sibyl, Adrian, Elara", "28/03/2023", "Hồ Quang Dũng", "Sibyl, the last enchanter of her kind, must harness her dwindling powers to save her kingdom. With Adrian, a charming rogue, and Elara, a fierce warrior, she embarks on a quest to reclaim her magic.Frost Queen and Emu graduate from college and live together in a small shared apartment , but rents getting tough and well , Emu refuses to beg from her family and since she took a break from her shows , shes not really earning anything , and Frost Queen . . Well , why would she of all people get herself dirty in peasent working areas ? Though unfortunately , her strict aura has only made interviewers fear her , even if she was being nice ."))
draft.append(Draft("The Keeper of Secrets", "Liora, Magnus, Freya", "05/12/2022", "Hồ Quang Dũng", "Liora, a guardian of ancient secrets, must protect her knowledge from those who seek to misuse it. With Magnus, a loyal friend, and Freya, a fierce warrior, she embarks on a journey to safeguard her legacy.The timeline of Sonic the Hedgehog is on the verge of destruction. Moments in time once concrete are now unknown. As a new enemies reveal themselves, it’s up to those on the outside to restore the past to save the future. That outsider is Rainbow Dash, and she’s in way over her head."))
draft.append(Draft("The Forgotten Song", "Melisande, Adrian, Lucian", "31/10/2020", "Hồ Quang Dũng", "Melisande, a talented bard, discovers an ancient song that holds the key to awakening a long-lost magic. With Adrian, a brooding warrior, and Lucian, a mysterious bard, they must protect the song from those who wish to misuse it.Additional chapters that are not from the main storyline and AU of an AU. I am taking requests, so if there is something you want me to do, please comment here. Requests are not guaranteed to be written.Following the events of Forgotten Friendship, Sunset Shimmer and her friends work together to construct a machine that will allow them to detect and locate Equestrian magic in their world."))
#chưa post
draft.append(Draft("Estacy", "Ulian, Suri", "28/07/2024", "Hồ Quang Dũng","Now that she was a ghost, she finally got to travel a lot, something she didn’t get to do when she was still alive. She no longer had to worry about feeding herself or keeping a roof above her head, what she terribly needed was entertainment. Something she found when she impulsively went to Siargao (airfare was free because nobody even knew she boarded the plane). She was exploring the beaches then when she got tired of the waves (who knew ghosts also got tired?) she went to see the villas. Probably the best decision she had ever done, both as a human and ghost. "))

#chờ duyệt
draft.append(Draft("Rolling down", "Namu, Yerky", "21/01/2025", "Hồ Quang Dũng","She was sitting on the hammock by the front porch when a man arrived. He had his sunglasses on, a Hawaiian shirt and khaki shorts paired with loafers (which, if you asked her, wasn’t really practical given that there were sand everywhere). He climbed up the stairs and fiddled with his keys as he tried to open the door. He had sighed for the nth time so she went closer to see him. She scanned his being. He was tall, very mestizo, he was brawny which had her thinking that beneath the shirt was a chiselled chest… probably abs too, and she couldn’t deny that he was pleasing to the eyes.She sat across him when he ate his dinner, almost jealous of him for being able to shovel down his throat that scrumptious looking steak. Her mouth watered the entire time. Why couldn’t she at least be allowed to eat ghost food?"))


for d in draft:
    print(d)
jff=JsonFileFactory()
filename= "../dataset/draft.json"
jff.write_data(draft,filename)

