# Form implementation generated from reading ui file 'D:\Users\LENOVO\baicuaThao\ProjectFinal\SignUp\SignUp.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1173, 809)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1171, 761))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\Users\\LENOVO\\baicuaThao\\ProjectFinal\\SignUp\\../image/3.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(530, 310, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    background: transparent;\n"
"    border: none;\n"
"}")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_LoginName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_LoginName.setGeometry(QtCore.QRect(530, 360, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_LoginName.setFont(font)
        self.lineEdit_LoginName.setStyleSheet("QLineEdit {\n"
"    background: transparent;\n"
"    border: none;\n"
"}")
        self.lineEdit_LoginName.setText("")
        self.lineEdit_LoginName.setObjectName("lineEdit_LoginName")
        self.lineEdit_Password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_Password.setGeometry(QtCore.QRect(530, 420, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_Password.setFont(font)
        self.lineEdit_Password.setStyleSheet("QLineEdit {\n"
"    background: transparent;\n"
"    border: none;\n"
"}")
        self.lineEdit_Password.setText("")
        self.lineEdit_Password.setObjectName("lineEdit_Password")
        self.lineEdit_UserName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_UserName.setGeometry(QtCore.QRect(530, 470, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_UserName.setFont(font)
        self.lineEdit_UserName.setStyleSheet("QLineEdit {\n"
"    background: transparent;\n"
"    border: none;\n"
"}")
        self.lineEdit_UserName.setText("")
        self.lineEdit_UserName.setObjectName("lineEdit_UserName")
        self.lineEdit_Email = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_Email.setGeometry(QtCore.QRect(530, 530, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_Email.setFont(font)
        self.lineEdit_Email.setStyleSheet("QLineEdit {\n"
"    background: transparent;\n"
"    border: none;\n"
"}")
        self.lineEdit_Email.setText("")
        self.lineEdit_Email.setObjectName("lineEdit_Email")
        self.pushButton_Back = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_Back.setGeometry(QtCore.QRect(400, 600, 141, 51))
        self.pushButton_Back.setText("")
        self.pushButton_Back.setFlat(True)
        self.pushButton_Back.setObjectName("pushButton_Back")
        self.pushButton_SignUp = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_SignUp.setGeometry(QtCore.QRect(630, 600, 141, 51))
        self.pushButton_SignUp.setText("")
        self.pushButton_SignUp.setFlat(True)
        self.pushButton_SignUp.setObjectName("pushButton_SignUp")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1173, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
